### ISSUE TITLE
Superfluous dependencies when used as a module

### ISSUE THREAD

**Issue by rndusr** [kz26/dottorrent#8]
I would like to use dottorrent as a module, but I don't want my project to depend on tqdm and humanfriendly which are only used by dottorrent's CLI. Is there any chance you would consider making a new dottorrent-cli project like dottorrent-gui?

Another thing I'm missing is a documented way to access the data dictionary. This is currently possible with a private `_data` variable, but a property with a docstring would be nicer.

Finally, I need a torrent file parser that provides all information in a pythonic way. I could implement this in my project, but I think it would be a useful feature in general.

I would make pull requests for the `data` property and a `TorrentInfo` class. What do you think?

**Comment by kz26** [comment]
Hi, I think splitting the library and CLI into separate packages is a reasonable thing to do. I'll try to have that sorted for the next release.

Refactoring _data into a public variable shouldn't be a problem either.

A torrent file parser, while useful, is a bit outside the scope of the project - to generate torrent files. Since torrents are just bencoded data any bencode parser should work: https://www.google.com/search?q=python+bencode+parser

No need to reinvent the wheel :P

**Comment by rndusr** [comment]
While bdecoding is easy enough it leaves you with utf-8 encoded strings, so it's a bit inconvenient.

But anyway, I grew impatient and made a fork/rewrite, and that's almost done now, so this issue is solved for me. I'll put a link it here in a few days.

**Comment by rndusr** [comment]
Here's my fork: https://github.com/rndusr/torf

**Comment by kz26** [comment]
Awesome!

**Comment by rndusr** [comment]
Thanks! Glad you like it. :)

And thanks for dottorrent. I honestly wouldn't have had any idea where to
start. It's so much easier to extend than to start from scratch.

**Comment by kz26** [comment]
The library and CLI have been split into their own packages as of version 1.10.0. Public access to the data dictionary is now implemented as well.
